site_name: mkdocs-meta
repo_url: https://github.com/anatoly-scherbakov/mkdocs-meta
repo_name: mkdocs-meta
copyright: Copyright &copy; 2020 Anatoly Scherbakov

nav:
  - RDFS: rdfs/index.md

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - meta
  - search
  - macros:
      modules:
        - mkdocs_meta

theme:
  name: semantic
  logo: None
